# Generated by Django 2.1.3 on 2019-02-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbpauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bussiness_account',
            field=models.BooleanField(default=False, help_text='ビジネスとしての利用かどうか、出品などプロ側の機能の権限付与', verbose_name='active'),
        ),
    ]
