# Generated by Django 2.1.3 on 2019-02-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbpauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='住所1'),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='住所2'),
        ),
    ]
