# Generated by Django 2.1.3 on 2019-02-09 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='購入枚数')),
                ('bought_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日')),
            ],
            options={
                'db_table': 'purchase',
                'verbose_name_plural': '購入履歴',
                'verbose_name': '購入履歴',
            },
        ),
    ]
