# Generated by Django 2.1.3 on 2019-02-09 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20190209_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='onayami_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_answer', to='tickets.OnayamiTicket'),
        ),
    ]
