# Generated by Django 2.1.3 on 2019-02-09 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20190209_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_review',
        ),
    ]
