# Generated by Django 2.1.3 on 2019-02-04 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190205_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='is_muryo',
            new_name='is_free',
        ),
    ]
