# Generated by Django 2.1.3 on 2019-02-09 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20190209_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '有料チケット', 'verbose_name_plural': '有料チケット'},
        ),
    ]
